### ISSUE TITLE
Fix logo path

### ISSUE THREAD

**Issue by Galope-Jhean** [PUP-BSIT/exercise-12-vrzn_webdev#1]
Good Day! please refer to your HTML and fix your logo directory

Link to your HTML File:
[Adrian Naoe](https://github.com/PUP-BSIT/exercise-12-vrzn_webdev/blob/main/naoe_adrian/naoe_adrian.html)
[Mark Odrunia](https://github.com/PUP-BSIT/exercise-12-vrzn_webdev/blob/main/Odrunia_Mark_Ryan/Odrunia_Mark_Ryan.html)

```<link rel="icon" href="../img/vrzn.png" type="img/x-icon">```

I suggest that you make this change

**Comment by Galope-Jhean** [comment]
@Odrunia-Mark-Ryan  
@Naoe-Adrian 

Please add a comment on this issue once you've fixed it.
If possible, feel free to submit a PR.

Thank you!

**Comment by Odrunia-Mark-Ryan** [comment]
logo path fixed

**Comment by Naoe-Adrian** [comment]
thanks for the heads up I already fix it :💯👌💡

**Comment by Galope-Jhean** [comment]
lgtm
