### ISSUE TITLE
Refactor JS code

### ISSUE THREAD

**Issue by go-christianharrel** [PUP-BSIT/exercise-12-vrzn_webdev#15]
https://github.com/PUP-BSIT/exercise-12-vrzn_webdev/blob/7678ae7de217e19c9900a32cb516e6b3007d0f95/dimasacat_andronicus/dimasacat_andronicus.js#L5

**Refactor to:**
`commentButton.disabled = !(name.length && comment.length);`

[See here]( https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g294850e169b_0_1) for your reference

**Comment by go-christianharrel** [comment]
@Dimasacat-Andronicus Good morning, Andronicus. I kindly request your review/changes of this issue before our class later. Have a pleasant breakfast, and looking forward to seeing you later!

**Comment by Dimasacat-Andronicus** [comment]
@go-christianharrel  Good morning, I genuinely like the adjustments, and I appreciate the feedback.
