### ISSUE TITLE
fix anchor tag path

### ISSUE THREAD

**Issue by Galope-Jhean** [PUP-BSIT/exercise-12-vrzn_webdev#2]
adhering to the [instructions](https://docs.google.com/presentation/d/1ek5_huVUox7BYBM3KVc9869tXuULxv61VnTkkuTOQyI/edit#slide=id.g24aaea973bc_0_51) that are given to us, please change the path of your anchor tag to "#"

@Naoe-Adrian : [HTML file](https://github.com/PUP-BSIT/exercise-12-vrzn_webdev/blob/main/naoe_adrian/naoe_adrian.html)

Refer to the anchor tags in your ```my-works-container``` div.

Below is a suggested change for your anchor tag: 

```
<a href="#"></a>
```

Thank You!

**Comment by Naoe-Adrian** [comment]
I clean it up tysm : )

**Comment by Galope-Jhean** [comment]
> I clean it up tysm : )

@Naoe-Adrian, would recommend that u remove the ```target="_blank"``` too. 

Thanks.

**Comment by Galope-Jhean** [comment]
changes lgtm, cool.
