### ISSUE TITLE
Exceeds 80-Character Line Limit & Anchor tag path

### ISSUE THREAD

**Issue by Naoe-Adrian** [PUP-BSIT/exercise-12-vrzn_webdev#6]
**_Jhean Galope:_**
 Please review your line column length related to the comment section, which can be found on lines 86, 205 and 222 Thank you .

```
<div class="details">
                  <h4>Christian Harrel Go</h4>
                  <p>We have similar goals, let's build community together sooner!</p>
</div>
```

```
 
  <form action="#">
                 <input type="text" id="input_name" placeholder="enter name">
                  <textarea name="comment" id="input_comment" placeholder="Enter your comment right here..."></textarea>
                   <button type="button" class="comment-btn" disabled>Comment</button>
  </form>
```

**_Andronicus Dimasacat_**:
 Fix your anchor tag and line column length as well you can scan your codes starts on line 82.

```
  <div class="works-style">
          <li>
            <a
              href="https://www.figma.com/file/r6KJwKWoKIqhE3EhaOHwe6/DIMASACAT_HCI_DESIGN?type=design&node-id=0%3A1&mode=design&t=oOBXIAebmb2Jyowx-1"
              target="blank"
              >Photo Editor Design in Figma</a
            >
          </li>
```

Refer to the anchor tags in your container-works div.

Below is a suggested change for your anchor tag:

`<a href="#"></a>`

@Odrunia-Mark-Ryan   Please review your line column length related to your works container, which can be found on lines 110-146

```
<b><a id="work_id" href="#" alt="work" target="_blank">Work 1</a></b>
            <p></p>
        </div>
        <div class="card-work">
            <div class="align">
                <span class="red"></span>
                <span class="yellow"></span>
                <span class="green"></span>
            </div>
            <b><a id="work_id" href="#" alt="work" target="_blank">Work 2</a></b>
 <p></p>
```
@go-christianharrel Please review your line column length related to the goals container, which can be found on lines 256
```
 <p>
            I'm convinced that the program/course I've chosen will open doors to
            a new path, allowing me to chase my dreams and fulfill my deepest
            passions.
  </p>
```

**Comment by Galope-Jhean** [comment]
made changes. would love a review thanks.

@Naoe-Adrian

**Comment by Dimasacat-Andronicus** [comment]
Done, thanks for the review. @Naoe-Adrian

**Comment by Galope-Jhean** [comment]
@Odrunia-Mark-Ryan: lines 110 and ff exceeds 80 cols
@go-christianharrel: refer to your container in line 228, there are ```<p>``` that exceeds 80 cols
your ```profile-description``` as well, checkout lines 178 and down too.

**Comment by go-christianharrel** [comment]
I have updated my html file following the guidelines. **Thank you!**

**Comment by Odrunia-Mark-Ryan** [comment]
Issues fixed, Thanks for the review

**Comment by go-christianharrel** [comment]
@Naoe-Adrian @JheanKhendrick Kindly close the issue once it is resolved. Thank you for your guidance!

**Comment by Galope-Jhean** [comment]
changes LGTM, everyone's code doesn't seem to go over 80 columns.

The longest column used was Harrell's in 

https://github.com/PUP-BSIT/exercise-12-vrzn_webdev/blob/e66aece99cb8385c810b230a061ced13c67799bf/go_christianharrel/go_christianharrel.html#L39

which used 80 columns.
